title: My Robot Project
description: Build guide and documentation
# theme: architect

# _config.yml
remote_theme: just-the-docs/just-the-docs@v0.5.2
# theme: documentation-theme
# theme: minimal-mistakes

# Optional: enable search
search_enabled: true

just_the_docs:
  navigation:
    structure: nested
  color_scheme: dark

  # Custom fonts
  fonts:
    body: "'Roboto', sans-serif"
    headings: "'Orbitron', sans-serif"